#!/usr/bin/env python3
"""build_skill.py — bundle the pure core + cs_skill reader + an in-CS kernel into ONE self-contained
``kernel.py`` (stdlib-only, zero intra-package imports) plus a ``SKILL.md``, and package/install it
as a Claude Science skill.

Inlining (vs vendoring ``core`` as a package) keeps the skill a two-file artifact and sidesteps the
"can a kernel import a package" question — a CS skill kernel is a single auto-loaded module. Our
stdlib-only core makes inlining a clean strip-imports-and-concatenate.

Modes (default = build):
  build       regenerate design/skill_dist/{kernel.py, SKILL.md, + assets}
  --zip       also write design/skill_dist/provenance-gate.zip  (for "Upload a skill" — one-time register)
  --share     stage kernel.py + SKILL.md + cockpit_template.html into ~/pg-share for the in-CS resync
  --watch     rebuild + --share on every save under src/ or design/ (the local auto-refresh loop)
  --name X    build/deploy under skill name X (default provenance-gate) — use a throwaway to validate first

Loop: `--zip` -> upload once to register -> then run `--watch` locally; each save rebuilds + stages to
~/pg-share, and in CS you run `pg_dev_sync()` (host.skills.edit from ~/pg-share) + a fresh conversation.
Uploaded skills aren't on disk and the kernel has no __file__ (both probed), so there is no symlink path.
"""

# ruff: noqa: E501 — a build script with inlined kernel/SKILL templates; some lines run long.

from __future__ import annotations

import pathlib
import sys
import zipfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "provenance_gate"
DIST = ROOT / "design" / "skill_dist"
SKILL_NAME = "provenance-gate"
# extra files shipped in the bundle, read at runtime via host.skills.read (not inlined into kernel.py)
ASSETS = {
    "cytoscape-dagre.bundle.min.js": ROOT / "ui" / "vendor" / "cytoscape-dagre.bundle.min.js",
    "cockpit_template.html": ROOT / "design" / "skill_assets" / "cockpit_template.html",
}

# core modules inlined in dependency order; the reader last (it uses derive + model)
MODULES = ["core/model.py", "core/derive.py", "core/audit.py", "adapters/cs_skill/host_query_reader.py"]

# The kernel header is just the module docstring + the hard constraints. The inlined modules KEEP
# their own stdlib/typing imports (they become function-level inside pg_impl), so adding a new import
# to a core module needs no change here and can't silently vanish from the kernel.
STDLIB_HEADER = (
    '"""__SKILL_NAME__ CS skill kernel — AUTO-GENERATED by design/build_skill.py. DO NOT EDIT HERE."""\n'
    "# No 'from __future__' (the CS plugin loader relocates the source, breaking its must-be-first\n"
    "# rule) and no slots=/PEP-604 unions — the control-plane repl kernel (host.query) is Python 3.9.\n"
)

# Drop ONLY these when inlining: __future__ (can't be relocated by the loader) and relative imports
# (their targets are inlined in-file). Every other import is kept, nested inside pg_impl.
_DROP_PREFIXES = ("from __future__", "from .")


def _strip_imports(src: str) -> str:
    keep = [ln for ln in src.splitlines() if not any(ln.lstrip().startswith(p) for p in _DROP_PREFIXES)]
    return "\n".join(keep).strip("\n")


def _core_bodies() -> str:
    parts = []
    for mod in MODULES:
        body = _strip_imports((SRC / mod).read_text())
        parts.append(f"# ================ inlined: provenance_gate/{mod} ================\n{body}")
    return "\n\n\n".join(parts)


def _kernel_source() -> str:
    # The CS sidecar gate rejects a kernel.py whose TOP LEVEL has _-prefixed names, classes, or
    # try/except — only functions, imports, and literal-constant assignments pass. So nest the ENTIRE
    # inlined core (dataclasses + _-helpers) inside one top-level pg_impl(host); the module top level
    # is then just imports + three functions. (The skill dir is also not on sys.path, so inlining, not
    # sibling imports, is required regardless.) Proven shape: merge-lineage-audit nests everything too.
    import textwrap
    nested = _core_bodies() + "\n\n\n" + KERNEL_IMPL
    return (
        STDLIB_HEADER
        + "\n\ndef pg_impl(host):\n"
        + textwrap.indent(nested, "    ")
        + '\n    return {"audit_project": audit_project, "audit_input_lineage": audit_input_lineage,'
        + '\n            "render_cockpit": render_cockpit}\n'
        + WRAPPERS
    ).replace(", slots=True", "").replace("__SKILL_NAME__", SKILL_NAME)


KERNEL_IMPL = '''

# ================ in-CS kernel (nested inside pg_impl(host)) ================
# host is pg_impl's arg (the CS-injected object). Reads via host.query(scope="project"), derives with
# the inlined core, judges with the inlined audit. Everything is nested so the module top level stays
# gate-clean; the top-level wrappers below call pg_impl(host)[...].


class _HostReader:
    """Adapt the injected ``host`` to the CsHost the reader wants: a project-scoped query returning
    list[dict]. Normalises host.query's shape ({rows,columns} tuple-rows OR dict-rows)."""

    def query(self, sql):
        result = host.query(sql, scope="project")  # noqa: F821  (host injected by CS)
        if isinstance(result, dict) and "rows" in result:
            rows = list(result["rows"])
            if not rows or isinstance(rows[0], dict):
                return rows
            cols = result.get("columns") or result.get("column_names") or result.get("fields") or []
            names = [c if isinstance(c, str) else (c.get("name") or c.get("id") or c.get("label") or str(c)) for c in cols]
            return [dict(zip(names, r)) for r in rows] if names else rows
        return [dict(r) for r in result]


def _reader():
    return HostQueryReader(_HostReader(), scope_by_host=True)


def _current_project_id():
    rows = _HostReader().query("SELECT id FROM projects LIMIT 1")
    return rows[0]["id"] if rows else "current"


def _issue(vi):
    return {"artifact": vi.artifact, "versions": list(vi.versions), "current": vi.current}


def audit_project():
    """Trust verdict for every computation in the current CS project: which cells consume a stale
    input (stale_input) or merge two live versions of one artifact (version_mix). Reuses core.audit."""
    g = _reader().read_project_graph(_current_project_id())
    verdicts = audit_graph(g)
    label = {n.id: n.label for n in g.nodes}
    flagged = sorted(
        (
            {"cell": label.get(nid, nid), "verdict": v.level,
             "stale": [_issue(s) for s in v.stale], "mixed": [_issue(m) for m in v.mixed]}
            for nid, v in verdicts.items() if v.level != CLEAN
        ),
        key=lambda f: f["cell"],
    )
    return {"project": g.cs_project_id, "cells": len(g.nodes),
            "clean": sum(1 for v in verdicts.values() if v.level == CLEAN), "flagged": flagged}


def audit_input_lineage(input_files, planned_output=None):
    """Pre-write check: given input filenames, the verdict over their latest versions' lineage
    (stale source / version mix) before you write ``planned_output``. Backed by core.audit —
    converges with the merge-lineage-audit helper on the tested engine."""
    if isinstance(input_files, str):
        input_files = [input_files]
    g = _reader().read_project_graph(_current_project_id())
    latest = {a.filename: a.artifact_version_id for n in g.nodes for a in n.output_surface if a.is_latest}
    vids, missing = [], []
    for f in input_files:
        if f in latest:
            vids.append(latest[f])
        else:
            missing.append(f)
    if not vids:
        return {"planned_output": planned_output, "missing_inputs": missing,
                "verdict": "LINEAGE_MISSING" if missing else "NOT_APPLICABLE"}
    v = audit_inputs(g, vids)
    return {"planned_output": planned_output, "missing_inputs": missing, "verdict": v.level,
            "stale": [_issue(s) for s in v.stale], "mixed": [_issue(m) for m in v.mixed]}


# ONE verdict->colour map + ONE node-view derivation, shared by the cytoscape elements and the static
# list. (The template legend swatches mirror these three hexes by hand.)
_VERDICT_COLOR = {CLEAN: "#33aa77", STALE_INPUT: "#e0a030", VERSION_MIX: "#dd2244"}


def _node_view(n, verdicts):
    v = verdicts.get(n.id)
    lvl = v.level if v else CLEAN
    arts = [i.artifact for i in ((list(v.mixed) + list(v.stale)) if v else [])]
    return lvl, _VERDICT_COLOR.get(lvl, "#33aa77"), arts


def _esc_html(s):
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _cyto_elements(g, verdicts):
    els = []
    for n in g.nodes:
        lvl, col, arts = _node_view(n, verdicts)
        els.append({"data": {"id": n.id, "label": n.label, "color": col, "detail": "; ".join(arts) or lvl}})
    for e in g.edges:
        els.append({"data": {"id": e.id, "source": e.src_node_id, "target": e.dst_node_id}})
    return els


def _node_list_html(g, verdicts):
    # static, server-rendered fallback: shows even when the viewer does not run the cytoscape JS
    lis = []
    for n in sorted(g.nodes, key=lambda x: x.label):
        lvl, col, arts = _node_view(n, verdicts)
        note = ""
        if lvl != CLEAN:
            note = " - " + lvl.replace("_", " ") + ((": " + "; ".join(arts)) if arts else "")
        lis.append('<li style="border-left-color:' + col + '">'
                   + _esc_html(n.label) + _esc_html(note) + "</li>")
    return "".join(lis) or "<li>no computation cells in this project yet</li>"


def render_cockpit():
    """Write the cockpit files: cockpit.html (project DAG, cells coloured by verdict) + the cytoscape
    cytoscape bundle referenced by its ARTIFACT MARKER ({{artifact:VID}} -> the served URL, the only
    <script src> form CS's HTTP viewer resolves). The bundle is a shared artifact saved once, so
    cockpit.html stays KB. First call (bundle not yet saved) returns the bundle for the agent to
    save_artifacts once; then this and later renders return cockpit.html to save_artifacts."""
    import json
    g = _reader().read_project_graph(_current_project_id())
    # The bundle must be a SAVED artifact so we can reference it by marker: {{artifact:VID}} is the only
    # <script src> form that resolves in CS's HTTP viewer (a bare filename or disk path 404s). Find its
    # version id; if it isn't saved yet, hand the bundle to the agent to save once, then re-run.
    rows = _HostReader().query(
        "SELECT v.id FROM artifact_versions v JOIN artifacts a ON a.id = v.artifact_id "
        "WHERE a.filename = 'cytoscape-dagre.bundle.min.js' ORDER BY v.version_number DESC")
    if not rows:
        b = host.skills.read("__SKILL_NAME__", "cytoscape-dagre.bundle.min.js")
        with open("cytoscape-dagre.bundle.min.js", "w", encoding="utf-8") as f:
            f.write(b["content"] if isinstance(b, dict) else b)
        return {"project": g.cs_project_id, "nodes": len(g.nodes), "status": "need_bundle_saved",
                "files": ["cytoscape-dagre.bundle.min.js"],
                "next": "save_artifacts(['cytoscape-dagre.bundle.min.js']) once, then call render_cockpit() again"}
    marker = host.artifact_marker(rows[0]["id"])   # "{{artifact:VID}}" -> the bundle's served URL
    t = host.skills.read("__SKILL_NAME__", "cockpit_template.html")
    t = t["content"] if isinstance(t, dict) else t
    verdicts = audit_graph(g)
    import re
    subs = {
        "__BUNDLE_SRC__": marker,   # {{artifact:VID}} marker; cockpit.html stays KB, not an inline bundle
        # escape '<' so an artifact named e.g. '</script>.csv' can't terminate the inline <script>
        "__ELEMENTS__": json.dumps(_cyto_elements(g, verdicts)).replace("<", chr(92) + "u003c"),
        "__NODELIST__": _node_list_html(g, verdicts),
    }
    # ONE pass: inserted values are never re-scanned, so a placeholder token appearing inside a
    # filename can't corrupt another slot.
    html = re.sub("|".join(re.escape(k) for k in subs), lambda m: subs[m.group(0)], t)
    with open("cockpit.html", "w", encoding="utf-8") as f:
        f.write(html)
    return {"project": g.cs_project_id, "nodes": len(g.nodes), "status": "rendered",
            "files": ["cockpit.html"], "next": "call save_artifacts(['cockpit.html']) to publish"}
'''


# gate-clean top level: only these public functions (+ pg_impl + imports) sit at module scope.
WRAPPERS = '''

def audit_project():
    return pg_impl(host)["audit_project"]()


def audit_input_lineage(input_files, planned_output=None):
    return pg_impl(host)["audit_input_lineage"](input_files, planned_output)


def render_cockpit():
    return pg_impl(host)["render_cockpit"]()


def pg_dev_sync():
    """DEV ONLY: resync this skill's files from ~/pg-share (build_skill --share) via host.skills.edit,
    then start a fresh conversation to load them. Strip before distributing."""
    import os
    base = os.path.expanduser("~/pg-share")
    for staged, path in (("__SKILL_NAME__.kernel.py", "kernel.py"),
                         ("__SKILL_NAME__.SKILL.md", "SKILL.md"),
                         ("__SKILL_NAME__.cockpit_template.html", "cockpit_template.html")):
        try:
            with open(base + "/" + staged, encoding="utf-8") as f:
                host.skills.edit("__SKILL_NAME__", path, f.read())
        except Exception as e:
            return "sync failed on " + path + ": " + repr(e)
    return "synced from ~/pg-share — start a fresh conversation to load the new kernel"
'''


SKILL_MD = '''---
name: __SKILL_NAME__
description: Deterministic trust audit over the current Claude Science project's provenance DAG. Call audit_project() for a per-cell verdict (which computations consume a stale input or merge two live versions of one artifact), or audit_input_lineage(files) before writing an output to check its inputs' lineage. Use when reasoning about whether a result is built on current, consistent upstream data.
---

# __SKILL_NAME__

Deterministic, claim-level provenance audit for the current project. Two helpers are auto-loaded
(definition-only); run them in the repl / control-plane surface (where `host.query` lives):

- **`audit_project()`** — a verdict for every computation cell: `stale_input` (consumes a
  non-current version of some artifact) or `version_mix` (its input lineage reconverges on two live
  versions of one artifact — a divergent-branch merge). Returns the flagged cells with the artifacts
  and version numbers in play.
- **`audit_input_lineage(input_files, planned_output=None)`** — before writing an output, check the
  latest versions of the named input files: same `stale_input` / `version_mix` verdict over their
  lineage closure.
- **`render_cockpit()`** — write an interactive `cockpit.html` (project DAG, each cell coloured by its
  verdict: clean / stale input / version mix), referencing the cytoscape bundle by its artifact marker
  so it stays KB. The first call returns the bundle to `save_artifacts` once; then it (and later renders)
  return `cockpit.html` to `save_artifacts`. Follow the returned `next` field.

All are computed from provenance alone (nothing stored) and are deterministic. A linear revision chain
(reading v1 to write v2) is a supersession, not a conflict, and is not flagged.
'''


def build() -> None:
    import shutil
    DIST.mkdir(parents=True, exist_ok=True)
    src = _kernel_source()
    compile(src, "kernel.py", "exec")   # fail LOUDLY here if the inliner produced invalid Python
    (DIST / "kernel.py").write_text(src)
    (DIST / "SKILL.md").write_text(SKILL_MD.replace("__SKILL_NAME__", SKILL_NAME))
    for name, src in ASSETS.items():
        shutil.copyfile(src, DIST / name)
    kb = (DIST / "kernel.py").stat().st_size
    print(f"built {DIST / 'kernel.py'} ({kb} bytes) + SKILL.md + {len(ASSETS)} assets")


def zip_() -> None:
    z = DIST / f"{SKILL_NAME}.zip"
    with zipfile.ZipFile(z, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.write(DIST / "kernel.py", "kernel.py")
        zf.write(DIST / "SKILL.md", "SKILL.md")
        for name in ASSETS:
            zf.write(DIST / name, name)
    print(f"packaged {z} ({z.stat().st_size // 1024} KB)  (upload via Skills -> Add skill -> Upload a skill)")


def share() -> None:
    # The dev loop. Uploaded skills are NOT on disk (probe: skill_dir_on_disk = not on disk) and the
    # kernel has no __file__, so there's no symlink/direct-write path. Instead stage the built files in
    # the sandbox-readable ~/pg-share (probe: pg_share_read = ok); in CS, host.skills.edit reads them.
    import shutil
    dst = pathlib.Path.home() / "pg-share"
    dst.mkdir(parents=True, exist_ok=True)
    for f in ("kernel.py", "SKILL.md", "cockpit_template.html"):
        shutil.copyfile(DIST / f, dst / f"{SKILL_NAME}.{f}")
    print(f"shared -> {dst}/{SKILL_NAME}.*  (in CS: run pg_dev_sync() + start a fresh conversation)")


def watch() -> None:
    import time
    targets = [ROOT / "src", ROOT / "design" / "build_skill.py", ROOT / "design" / "skill_assets"]

    def snap():
        s = {}
        for t in targets:
            if t.is_file():
                s[t] = t.stat().st_mtime
            else:
                for p in list(t.rglob("*.py")) + list(t.rglob("*.html")):
                    s[p] = p.stat().st_mtime
        return s

    print("watching src/ + design/ — rebuild + --share on save (Ctrl-C to stop)")
    last = None
    while True:
        cur = snap()
        if cur != last:
            build()
            share()
            print("  [rebuilt + shared] -> run pg_dev_sync() in CS + start a fresh conversation")
            last = cur
        time.sleep(1.0)


def main(argv: list[str]) -> None:
    global SKILL_NAME
    if "--name" in argv:
        idx = argv.index("--name")
        if idx + 1 >= len(argv):
            sys.exit("--name requires a value")
        SKILL_NAME = argv[idx + 1]
    if "--watch" in argv:
        watch()
        return
    build()
    if "--zip" in argv:
        zip_()
    if "--share" in argv:
        share()


if __name__ == "__main__":
    main(sys.argv[1:])
