#!/usr/bin/env python3
"""build_skill.py — bundle the pure core + cs_skill reader + an in-CS kernel into ONE self-contained
``kernel.py`` (stdlib-only, zero intra-package imports) plus a ``SKILL.md``, and package/install it
as a Claude Science skill.

Inlining (vs vendoring ``core`` as a package) keeps the skill a two-file artifact and sidesteps the
"can a kernel import a package" question — a CS skill kernel is a single auto-loaded module. Our
stdlib-only core makes inlining a clean strip-imports-and-concatenate.

Modes (default = build):
  build       regenerate design/skill_dist/{kernel.py, SKILL.md, + assets}
  --zip       also write design/skill_dist/provenance-gate.zip  (for "Upload a skill" — one-time register)
  --share     stage kernel.py + SKILL.md + cockpit_template.html into ~/pg-share for the in-CS resync
  --watch     rebuild + --share on every save under src/ or design/ (the local auto-refresh loop)
  --name X    build/deploy under skill name X (default provenance-gate) — use a throwaway to validate first

Loop: `--zip` -> upload once to register -> then run `--watch` locally; each save rebuilds + stages to
~/pg-share, and in CS you run `pg_dev_sync()` (host.skills.edit from ~/pg-share) + a fresh conversation.
Uploaded skills aren't on disk and the kernel has no __file__ (both probed), so there is no symlink path.
"""

# ruff: noqa: E501 — a build script with inlined kernel/SKILL templates; some lines run long.

from __future__ import annotations

import pathlib
import sys
import zipfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "provenance_gate"
DIST = ROOT / "design" / "skill_dist"
SKILL_NAME = "provenance-gate"
# extra files shipped in the bundle, read at runtime via host.skills.read (not inlined into kernel.py).
ASSETS = {
    "cytoscape-dagre.bundle.min.js": ROOT / "ui" / "vendor" / "cytoscape-dagre.bundle.min.js",
}
# GENERATED from ui/cockpit.html by _skill_cockpit_html: the tiny shell + the saved-once app JS (CSS
# folded in) that render_cockpit references by marker (so the ~97KB app is saved once, not per render).
GENERATED = ("cockpit_template.html", "cockpit-app.js")

# core modules inlined in dependency order; the reader last (it uses derive + model)
MODULES = ["core/model.py", "core/walk.py", "core/derive.py", "core/audit.py",
           "core/subgraph.py", "core/review_kit.py", "adapters/cs_skill/host_query_reader.py"]


# ---- the in-CS cockpit template, generated from ui/cockpit.html at build time ----
# The full cockpit is ~770KB (vendor + app CSS + app JS). In-CS each render_cockpit would re-save that,
# so we markerize the three big STATIC pieces as saved-once artifacts referenced by {{artifact:VID}}:
# the ~670KB vendor bundle, the ~32KB app CSS (<style> -> <link>), and the ~65KB app JS (the app <script>
# -> <script src>). The generated shell is then just the DOM + three marker refs + the per-render baked
# graph (PG:SKILL-DATA) + a no-bundle fallback — KB, not ~770KB. PG:DATA-IO reads the injected globals
# (the data-provider seam), so the app JS can live in an external file that boots AFTER PG:SKILL-DATA.
SKILL_DATA_BLOCK = '''
// ===== PG:SKILL-DATA — generated by build_skill.py; do not edit. In-CS there is no server, so the
// cockpit's PG:DATA-IO getProjects/getGraph serve these injected globals (baked once by render_cockpit)
// instead of fetching /api. Set BEFORE the app <script src> so getGraph reads them when the app boots. =====
window.__PG_PROJECT = __PROJECT__;   // {id, name}
window.__PG_GRAPH = __GRAPH__;       // core.audit.graph_response shape (asdict(graph) + per-node verdict)
window.__PG_SNAPSHOT = true;         // static snapshot: cockpit shows the bake date, not a pulsing live poll
// ===== /PG:SKILL-DATA ====='''

# D1 minimal fallback: if the vendor bundle didn't load (cytoscape undefined), show a static node list
# from the baked graph instead of a blank page. Inert once cytoscape is present.
SKILL_FALLBACK_BLOCK = '''
<div id="pg-skill-fallback" style="display:none;position:fixed;inset:0;overflow:auto;padding:64px 24px;
  font:14px/1.6 system-ui,sans-serif;background:#0f1115;color:#e8eaed;z-index:9999">
  <h2 style="margin:0 0 6px">Provenance cockpit</h2>
  <p style="opacity:.7;margin:0 0 16px">The cytoscape bundle didn't load in this viewer — download this
  file and open it in a browser for the interactive DAG. Cells in this project:</p>
  <ul id="pg-skill-fallback-list" style="list-style:none;padding:0;margin:0;max-width:720px"></ul>
</div>
<script>
addEventListener('DOMContentLoaded', function () {
  if (typeof cytoscape !== 'undefined') return;   // bundle loaded -> the real cockpit runs
  var g = window.__PG_GRAPH || { nodes: [] };
  var col = { clean: '#33aa77', stale_input: '#e0a030', version_mix: '#dd2244' };
  var esc = function (s) { return String(s).replace(/[&<>]/g, function (c) { return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' })[c]; }); };
  document.getElementById('pg-skill-fallback-list').innerHTML = (g.nodes || [])
    .slice().sort(function (a, b) { return (a.label || '').localeCompare(b.label || ''); })
    .map(function (n) {
      var lvl = (n.verdict && n.verdict.level) || 'clean';
      return '<li style="padding:9px 13px;margin:7px 0;border-radius:8px;background:#171a21;border-left:4px solid '
        + (col[lvl] || col.clean) + '">' + esc(n.label) + (lvl !== 'clean' ? ' \\u2014 ' + lvl.replace('_', ' ') : '') + '</li>';
    }).join('') || '<li>no computation cells in this project yet</li>';
  document.getElementById('pg-skill-fallback').style.display = 'block';
});
</script>
'''


def _skill_cockpit_html():
    """Generate the in-CS cockpit from ui/cockpit.html, returning (shell, app_js). The shell is tiny:
    DOM + marker refs to the saved-once vendor bundle + app JS + inline PG:SKILL-DATA (the per-render
    baked graph) + a no-bundle fallback. The ~32KB app CSS is folded into app_js (injected as a <style>
    on load), so both the CSS and the ~65KB JS ride ONE saved-once <script src> marker — no <link>, whose
    marker rewrite the CS viewer isn't known to resolve. render_cockpit fills the markers + baked data."""
    import json
    design_dir = str(ROOT / "design")
    if design_dir not in sys.path:   # don't accumulate copies across a watch()-loop's rebuilds
        sys.path.insert(0, design_dir)
    import vendor_libs
    html = vendor_libs.strip_vendor((ROOT / "ui" / "cockpit.html").read_text())
    if "</head>" not in html:
        sys.exit("build_skill: no </head> in ui/cockpit.html — cannot place the vendor <script src>")
    html = html.replace("</head>", '<script src="__BUNDLE_SRC__"></script>\n</head>', 1)
    # pull the app CSS out of the shell; it rides inside app_js (injected as a <style> when app_js loads)
    if "<style>" not in html or "</style>" not in html:
        sys.exit("build_skill: no <style> block in ui/cockpit.html")
    a, b = html.index("<style>"), html.index("</style>") + len("</style>")
    app_css = html[a + len("<style>"):html.index("</style>")]
    html = html[:a] + "<!-- app CSS is injected by cockpit-app.js -->" + html[b:]
    # the app <script> (PG:DATA-IO .. boot) -> a saved-once artifact; inline PG:SKILL-DATA (per-render
    # baked globals) goes BEFORE the marker so PG:DATA-IO's getGraph reads it when the external app boots.
    if "// ===== PG:DATA-IO" not in html:
        sys.exit("build_skill: no PG:DATA-IO in ui/cockpit.html — can't find the app <script>")
    d = html.index("// ===== PG:DATA-IO")
    o = html.rindex("<script>", 0, d)
    c = html.index("</script>", d)
    app_js = ("(function(){var s=document.createElement('style');s.textContent="
              + json.dumps(app_css) + ";document.head.appendChild(s);})();\n"
              + html[o + len("<script>"):c])
    html = (html[:o] + "<script>" + SKILL_DATA_BLOCK + "\n</script>\n"
            + '<script src="__APP_JS_SRC__"></script>' + html[c + len("</script>"):])
    if "</body>" not in html:
        sys.exit("build_skill: no </body> in ui/cockpit.html — cannot place the fallback")
    html = html.replace("</body>", SKILL_FALLBACK_BLOCK + "</body>", 1)
    return html, app_js

# The kernel header is just the module docstring + the hard constraints. The inlined modules KEEP
# their own stdlib/typing imports (they become function-level inside pg_impl), so adding a new import
# to a core module needs no change here and can't silently vanish from the kernel.
STDLIB_HEADER = (
    '"""__SKILL_NAME__ CS skill kernel — AUTO-GENERATED by design/build_skill.py. DO NOT EDIT HERE."""\n'
    "# No 'from __future__' (the CS plugin loader relocates the source, breaking its must-be-first\n"
    "# rule) and no slots=/PEP-604 unions — the control-plane repl kernel (host.query) is Python 3.9.\n"
)

# Drop ONLY these when inlining: __future__ (can't be relocated by the loader) and relative imports
# (their targets are inlined in-file). Every other import is kept, nested inside pg_impl.
_DROP_PREFIXES = ("from __future__", "from .")


def _strip_imports(src: str) -> str:
    keep = [ln for ln in src.splitlines() if not any(ln.lstrip().startswith(p) for p in _DROP_PREFIXES)]
    return "\n".join(keep).strip("\n")


def _core_bodies() -> str:
    parts = []
    for mod in MODULES:
        body = _strip_imports((SRC / mod).read_text())
        parts.append(f"# ================ inlined: provenance_gate/{mod} ================\n{body}")
    return "\n\n\n".join(parts)


def _kernel_source() -> str:
    # The CS sidecar gate rejects a kernel.py whose TOP LEVEL has _-prefixed names, classes, or
    # try/except — only functions, imports, and literal-constant assignments pass. So nest the ENTIRE
    # inlined core (dataclasses + _-helpers) inside one top-level pg_impl(host); the module top level
    # is then just imports + three functions. (The skill dir is also not on sys.path, so inlining, not
    # sibling imports, is required regardless.) Proven shape: merge-lineage-audit nests everything too.
    import textwrap
    nested = _core_bodies() + "\n\n\n" + KERNEL_IMPL
    return (
        STDLIB_HEADER
        + "\n\ndef pg_impl(host):\n"
        + textwrap.indent(nested, "    ")
        + '\n    return {"audit_project": audit_project, "audit_input_lineage": audit_input_lineage,'
        + '\n            "render_cockpit": render_cockpit, "review_subgraph": review_subgraph,'
        + '\n            "review_chat": review_chat, "review_selection": review_selection}\n'
        + WRAPPERS
    ).replace(", slots=True", "").replace("__SKILL_NAME__", SKILL_NAME)


KERNEL_IMPL = '''

# ================ in-CS kernel (nested inside pg_impl(host)) ================
# host is pg_impl's arg (the CS-injected object). Reads via host.query(scope="project"), derives with
# the inlined core, judges with the inlined audit. Everything is nested so the module top level stays
# gate-clean; the top-level wrappers below call pg_impl(host)[...].


class _HostReader:
    """Adapt the injected ``host`` to the CsHost the reader wants: a project-scoped query returning
    list[dict]. Normalises host.query's shape ({rows,columns} tuple-rows OR dict-rows)."""

    def query(self, sql):
        result = host.query(sql, scope="project")  # noqa: F821  (host injected by CS)
        if isinstance(result, dict) and "rows" in result:
            rows = list(result["rows"])
            if not rows or isinstance(rows[0], dict):
                return rows
            cols = result.get("columns") or result.get("column_names") or result.get("fields") or []
            names = [c if isinstance(c, str) else (c.get("name") or c.get("id") or c.get("label") or str(c)) for c in cols]
            return [dict(zip(names, r)) for r in rows] if names else rows
        return [dict(r) for r in result]


def _reader():
    return HostQueryReader(_HostReader(), scope_by_host=True)


def _current_frame():
    """The current conversation, from the CS repl kernel's CWD: its basename IS the current frame id;
    resolve it to (root_frame_id, project_id). root_frame_id is the whole conversation — a delegated
    sub-agent frame still maps to its chat's root — and project_id is a DETERMINISTIC current project.
    Returns (None, None) when it can't resolve (not a repl CWD, an unknown id, or a legacy schema
    without these columns), so callers fall back to the heuristic project or report no current chat."""
    import os
    try:
        fid = os.path.basename(os.getcwd())   # getcwd inside the guard: a deleted CWD raises OSError
        if not fid:
            return None, None
        rows = _HostReader().query(
            "SELECT root_frame_id, project_id FROM frames WHERE id = '" + _esc(fid) + "'")
    except Exception:
        return None, None
    if rows:
        return rows[0].get("root_frame_id") or fid, rows[0].get("project_id")
    return None, None


def _project_named(pid):
    # {id, name} for a known project id (name looked up) — used once _current_frame hands us the id.
    rows = _HostReader().query("SELECT name FROM projects WHERE id = '" + _esc(pid) + "'")
    return {"id": pid, "name": (rows[0].get("name") if rows else None) or pid}


def _recency_project():
    # Fallback when there's no current frame: the most-recently-updated project (matching
    # adapters/external/substrate.list_projects). Never hard-fails — a sentinel if projects is empty.
    rows = _HostReader().query("SELECT id, name FROM projects ORDER BY updated_at DESC LIMIT 1")
    if rows:
        return {"id": rows[0]["id"], "name": rows[0].get("name") or rows[0]["id"]}
    return {"id": "current", "name": "current"}


def _current_project():
    # The DETERMINISTIC current project — the current frame's project (CWD-derived); recency fallback
    # when the frame can't be resolved (off a repl CWD or a legacy schema), so this never hard-fails.
    _root, pid = _current_frame()
    return _project_named(pid) if pid else _recency_project()


def _current_project_id():
    return _current_project()["id"]


def audit_project():
    """Trust verdict for every computation in the current CS project: which cells consume a stale
    input (stale_input) or merge two live versions of one artifact (version_mix). Reuses core.audit."""
    g = _reader().read_project_graph(_current_project_id())
    verdicts = audit_graph(g)
    label = {n.id: n.label for n in g.nodes}
    flagged = flagged_verdicts(verdicts, label)   # the one flag serializer, shared with review_kit
    return {"project": g.cs_project_id, "cells": len(g.nodes),
            "clean": sum(1 for v in verdicts.values() if v.level == CLEAN), "flagged": flagged}


def audit_input_lineage(input_files, planned_output=None):
    """Pre-write check before you write ``planned_output`` from these input files. Flags two things the
    filenames alone don't reveal: (1) MERGING these inputs would collide on divergent versions of one
    artifact (a version_mix in their combined lineage), and (2) the inputs already REST on flagged data —
    a stale or mixed cell in their FOUNDATION (ancestry), e.g. an input that is the current version of its
    artifact but was itself built from a since-superseded source. Backed by core.audit."""
    if isinstance(input_files, str):
        input_files = [input_files]
    reader = _reader()
    pid = _current_project_id()
    g = reader.read_project_graph(pid)
    latest = {a.filename: a.artifact_version_id for n in g.nodes for a in n.output_surface if a.is_latest}
    vids, missing = [], []
    for f in input_files:
        if f in latest:
            vids.append(latest[f])
        else:
            missing.append(f)
    if not vids:
        return {"planned_output": planned_output, "missing_inputs": missing,
                "verdict": "LINEAGE_MISSING" if missing else "NOT_APPLICABLE"}
    combo = audit_inputs(g, vids)                             # mix from MERGING the inputs (hypothetical node)
    cone = reader.read_graph(pid, seeds=vids)                 # the inputs' own FOUNDATION (their ancestry)
    foundation = flagged_verdicts(audit_graph(cone), {n.id: n.label for n in cone.nodes})
    mix = combo.level == VERSION_MIX or any(f["verdict"] == VERSION_MIX for f in foundation)
    stale = bool(combo.stale) or any(f["verdict"] == STALE_INPUT for f in foundation)
    return {"planned_output": planned_output, "missing_inputs": missing,
            "verdict": VERSION_MIX if mix else STALE_INPUT if stale else CLEAN,
            "mixed": issues(combo.mixed), "stale": issues(combo.stale), "foundation": foundation}


def _resolve_cone(reader, proj, refs):
    """Resolve seed refs (a filename / id, or a list) to a lineage cone. Returns (normalised_refs,
    graph); graph is None when nothing resolved, so the caller formats its own *_unresolved status."""
    refs = sorted(refs) if isinstance(refs, (set, frozenset)) else refs  # JSON-safe + stable
    seeds = reader.resolve_seeds(proj["id"], refs)
    if not seeds:
        return refs, None
    return refs, reader.read_graph(proj["id"], seeds=seeds)


def render_cockpit(focus=None):
    """Write cockpit.html: the interactive cockpit for the current CS project as a static snapshot
    (inspector, rail, trace, isolate, flow toggle, framed DAG). The two big STATIC pieces — the cytoscape
    bundle and the app JS (CSS folded in) — are SAVED-ONCE artifacts referenced by their ARTIFACT MARKER
    ({{artifact:VID}} -> served URL, the only <script src> CS's HTTP viewer resolves), so each render
    writes only a KB shell + the baked graph, not the ~770KB whole. First call saves any not-yet-saved
    asset; follow the returned `next`, then re-run to publish cockpit.html.

    ``focus`` (a filename / artifact id / version id, or a list of them) renders only that seed's
    UPSTREAM lineage cone — everything it transitively depends on — instead of the whole project; the
    verdicts stay certain (a newer version off the cone is still flagged stale). Omit it for the full
    project. A filename seeds ALL of that artifact's versions."""
    import json
    import re
    proj = _current_project()
    reader = _reader()
    if focus is not None:  # None = full project; an EMPTY focus ([]/"") is a request that matched nothing
        focus, g = _resolve_cone(reader, proj, focus)
        if g is None:
            return {"project": proj["id"], "status": "focus_unresolved", "focus": focus,
                    "next": "focus matched no artifact/version in this project — check the name"}
    else:
        g = reader.read_graph(proj["id"])
    scope = {"focus": focus}   # uniform shape: focus is None for a full-project render
    # each big static asset must be a SAVED artifact so we can reference it by marker ({{artifact:VID}} is
    # the only <script src> CS's viewer resolves). Look each up by filename; write + collect any not yet
    # saved, and hand them ALL to the agent to save_artifacts once, then re-run.
    assets = [("cytoscape-dagre.bundle.min.js", "__BUNDLE_SRC__"),
              ("cockpit-app.js", "__APP_JS_SRC__")]
    subs, unsaved = {}, []
    reader = _HostReader()   # stateless; one instance for the whole asset loop
    for filename, placeholder in assets:
        rows = reader.query(
            "SELECT v.id FROM artifact_versions v JOIN artifacts a ON a.id = v.artifact_id "
            "WHERE a.filename = '" + _esc(filename) + "' ORDER BY v.version_number DESC")
        if rows:
            subs[placeholder] = host.artifact_marker(rows[0]["id"])   # {{artifact:VID}} -> served URL
        else:
            b = host.skills.read("__SKILL_NAME__", filename)
            with open(filename, "w", encoding="utf-8") as f:
                f.write(b["content"] if isinstance(b, dict) else b)
            unsaved.append(filename)
    if unsaved:
        call = "render_cockpit(focus=" + json.dumps(focus) + ")" if focus else "render_cockpit()"
        return {"project": g.cs_project_id, "nodes": len(g.nodes), "scope": scope,
                "status": "need_assets_saved", "files": unsaved,
                "next": "save_artifacts(" + json.dumps(unsaved) + ") once, then call " + call + " again"}
    t = host.skills.read("__SKILL_NAME__", "cockpit_template.html")
    t = t["content"] if isinstance(t, dict) else t
    # the getGraph wire shape from the ONE shared serializer (core.audit.graph_response, inlined) —
    # identical to what adapters/external/server.py serves, so the two surfaces can't drift.
    resp = graph_response(g)
    # escape EVERY '<' as \\u003c (valid JSON; '<' only appears inside string values). The baked GRAPH is
    # a live JS object literal in an inline <script>; a '</'-only seal misses the <!--<script> double-escape.
    # chr(92) is a backslash, on purpose: this line is inside the KERNEL_IMPL string, so writing the escape
    # literally would collapse to a bare '<' in the generated kernel and make seal a no-op.
    seal = lambda s: s.replace("<", chr(92) + "u003c")
    subs["__GRAPH__"] = seal(json.dumps(resp))
    subs["__PROJECT__"] = seal(json.dumps({"id": proj["id"], "name": proj["name"]}))
    # ONE pass: inserted values are never re-scanned, so a placeholder token in a baked value can't
    # corrupt another slot.
    html = re.sub("|".join(re.escape(k) for k in subs), lambda m: subs[m.group(0)], t)
    with open("cockpit.html", "w", encoding="utf-8") as f:
        f.write(html)
    return {"project": g.cs_project_id, "nodes": len(g.nodes), "scope": scope, "status": "rendered",
            "files": ["cockpit.html"], "next": "call save_artifacts(['cockpit.html']) to publish"}


def review_subgraph(nodes, scope="upstream"):
    """A deterministic review brief over a chosen lineage subgraph. Resolve ``nodes`` (a filename /
    artifact id / version id, or a list of them) to seeds, read their UPSTREAM cone, and hand back the
    evidence — flagged conflicts, lineage edges, artifact inventory, and the cell ids to fetch code
    for. Fixes WHAT to look at (same nodes -> same brief); the agent reasons and may walk deeper.
    Backed by core.review_kit; ``scope`` is a passthrough label for now (upstream cone)."""
    proj = _current_project()
    reader = _reader()
    nodes, g = _resolve_cone(reader, proj, nodes)
    if g is None:
        return {"project": proj["id"], "status": "seeds_unresolved", "nodes": nodes,
                "next": "none matched an artifact/version in this project; check the names/ids"}
    return review_kit(g, scope)


def review_chat(scope="upstream"):
    """A deterministic review brief scoped to THIS conversation: seed it with the artifacts this chat
    produced, then read their UPSTREAM cone and hand back the evidence (flagged conflicts, lineage,
    inventory, cells). The seeds are just this chat's outputs, but the cone + audit reach versions made
    in OTHER conversations — so a divergent version created elsewhere still surfaces as a conflict here.
    No args: it resolves the current chat itself. Use review_subgraph(<names>) to scope by hand instead.
    Backed by core.review_kit; ``scope`` is a passthrough label for now (upstream cone)."""
    root, pid = _current_frame()   # resolve the current conversation ONCE (root + project id together)
    proj = _project_named(pid) if pid else _recency_project()
    if not root:
        return {"project": proj["id"], "status": "no_current_chat",
                "next": "couldn't resolve the current conversation; use review_subgraph(<names>) to scope explicitly"}
    reader = _reader()
    seeds = reader.chat_seeds(proj["id"], root)
    if not seeds:
        return {"project": proj["id"], "status": "chat_empty", "root_frame": root,
                "next": "this conversation has produced no artifacts yet — nothing to review"}
    kit = review_kit(reader.read_graph(proj["id"], seeds=seeds), scope)
    kit["chat_scoped"] = True
    return kit


def _trusted_inputs(graph, keep):
    # the DIRECT dependencies crossing INTO the selection from EXCLUDED producers — the human's trust
    # cut. Not drawn in the induced brief, but the agent should know what the selection rests on. Deduped
    # by via-version (one row per distinct external version — two picked nodes sharing an input collapse
    # to one), so a version_mix's TWO live versions still both appear. Reuses review_kit's _via_fields.
    ref_of = _ref_map(graph)
    label = {n.id: n.label for n in graph.nodes}
    seen, out = set(), []
    for e in graph.edges:
        v = e.via_artifact_version_id
        if e.dst_node_id in keep and e.src_node_id not in keep and v not in seen:
            seen.add(v)
            row = _via_fields(ref_of.get(v), v)
            row["from"] = label.get(e.src_node_id, e.src_node_id)
            out.append(row)
    out.sort(key=lambda r: (r["from"], r["artifact"], r["version"] or 0))
    return out


def review_selection(nodes, scope="selection"):
    """A deterministic review brief over EXACTLY the picked nodes — a hand-selected region from the
    cockpit. The STRUCTURE is INDUCED down to just those nodes and the edges among them (no full
    lineage cone dumped on the agent), but the VERDICTS are taken from the FULL-project audit, so the
    flags on the shown nodes match exactly what the cockpit colours them. That lets you hand the agent
    a suspicious fork, cut the trusted trunk out of the picture, and still have every stale_input /
    version_mix reflect the whole graph — a conflict can rest on inputs that aren't drawn here, so
    ``trusted_inputs`` lists what the selection consumes from outside itself. Resolve ``nodes``
    (version ids, or filenames / artifact ids) to the selection. Backed by core.induced_subgraph +
    core.review_kit."""
    proj = _current_project()
    reader = _reader()
    selected = reader.resolve_seeds(proj["id"], nodes)   # -> version ids (self-artifacts dropped)
    if not selected:
        return {"project": proj["id"], "status": "seeds_unresolved", "nodes": nodes,
                "next": "none matched an artifact/version in this project; check the names/ids"}
    full = reader.read_project_graph(proj["id"])   # the AUTHORITATIVE graph — same basis as the cockpit
    producer_of = _producer_map(full)              # version id -> its producing node (shared with audit)
    keep = {producer_of[v] for v in selected if v in producer_of}
    if not keep:   # versions resolved but none has a producing node in the graph — an inconsistent
        return {"project": proj["id"], "status": "seeds_no_producers", "nodes": nodes,   # DB, not an
                "next": "the selected versions have no producing cell in this project (unexpected — the graph may be inconsistent)"}
    kit = review_kit(induced_subgraph(full, keep), scope, verdicts=audit_graph(full))
    kit["basis"] = "full_project_audit"
    kit["trusted_inputs"] = _trusted_inputs(full, keep)
    kit["note"] = ("induced subgraph — only the selected nodes and the edges among them are shown, "
                   "NOT a full lineage cone. The flags come from the FULL-project audit, so a flag can "
                   "name an artifact that isn't drawn here — each flag's mixed/stale field names the "
                   "exact artifact + versions behind it. 'boundary' lists only sources INSIDE the "
                   "selection (empty when you cut the trunk); 'trusted_inputs' is the real upstream "
                   "boundary — the direct dependencies the selection consumes from the excluded region.")
    return kit
'''


# gate-clean top level: only these public functions (+ pg_impl + imports) sit at module scope.
WRAPPERS = '''

def audit_project():
    return pg_impl(host)["audit_project"]()


def audit_input_lineage(input_files, planned_output=None):
    return pg_impl(host)["audit_input_lineage"](input_files, planned_output)


def render_cockpit(focus=None):
    return pg_impl(host)["render_cockpit"](focus)


def review_subgraph(nodes, scope="upstream"):
    return pg_impl(host)["review_subgraph"](nodes, scope)


def review_chat(scope="upstream"):
    return pg_impl(host)["review_chat"](scope)


def review_selection(nodes, scope="selection"):
    return pg_impl(host)["review_selection"](nodes, scope)


def pg_dev_sync():
    """DEV ONLY: resync this skill's files from ~/pg-share (build_skill --share) via host.skills.edit,
    then start a fresh conversation to load them. Strip before distributing."""
    import os
    base = os.path.expanduser("~/pg-share")
    # cockpit-app.js is a saved-once artifact: syncing the skill file here won't refresh an already-saved
    # artifact — delete the cockpit-app.js artifact (+ re-render) after a cockpit change to re-save it.
    for path in ("kernel.py", "SKILL.md", "cockpit_template.html", "cockpit-app.js"):
        try:
            with open(base + "/__SKILL_NAME__." + path, encoding="utf-8") as f:
                host.skills.edit("__SKILL_NAME__", path, f.read())
        except Exception as e:
            return "sync failed on " + path + ": " + repr(e)
    return "synced from ~/pg-share — start a fresh conversation to load the new kernel"
'''


SKILL_MD = '''---
name: __SKILL_NAME__
description: Deterministic trust audit over the current Claude Science project's provenance DAG. Call audit_project() for a per-cell verdict (which computations consume a stale input or merge two live versions of one artifact), audit_input_lineage(files) before writing an output to check its inputs' lineage, review_chat() for an evidence brief scoped to what THIS conversation produced, review_subgraph(nodes) for a brief over a hand-picked lineage subgraph, or review_selection(nodes) for a brief over exactly the picked nodes (a fork, minus a trusted trunk) to ground a review. Use when reasoning about whether a result is built on current, consistent upstream data.
---

# __SKILL_NAME__

Deterministic, claim-level provenance audit for the current project. Two helpers are auto-loaded
(definition-only); run them in the repl / control-plane surface (where `host.query` lives):

- **`audit_project()`** — a verdict for every computation cell: `stale_input` (consumes a
  non-current version of some artifact) or `version_mix` (its input lineage reconverges on two live
  versions of one artifact — a divergent-branch merge). Returns the flagged cells with the artifacts
  and version numbers in play.
- **`audit_input_lineage(input_files, planned_output=None)`** — before writing an output from the named
  input files, check what their filenames don't reveal: `version_mix` if MERGING them collides on
  divergent versions of one artifact, and `stale_input` / `version_mix` in their FOUNDATION — a flagged
  cell in the inputs' own ancestry (e.g. an input that is the current version of its artifact but was
  itself built from a since-superseded source). The flagged foundation cells come back in `foundation`.
- **`render_cockpit(focus=None)`** — write an interactive `cockpit.html` (project DAG, each cell
  coloured by its verdict: clean / stale input / version mix), referencing the cytoscape bundle by its
  artifact marker so it stays KB. The first call returns the static assets to `save_artifacts` once;
  then it (and later renders) return `cockpit.html` to `save_artifacts`. Follow the returned `next`
  field. Pass `focus` (a filename / artifact id / version id, or a list) to render only that seed's
  **upstream lineage cone** — everything it transitively depends on — instead of the whole project;
  the verdicts stay certain (a newer version off the cone is still flagged stale). A filename seeds
  every version of that artifact.
- **`review_chat(scope="upstream")`** — the same **review brief**, but scoped to THIS conversation:
  no args needed, it seeds from the artifacts this chat produced and reads their upstream cone. The
  cone and audit still reach versions made in *other* conversations, so a divergent version created
  elsewhere surfaces here as a conflict — the chat is the entry point, not a blindfold. Use it for a
  quick "is what I just made trustworthy?" without naming files.
- **`review_subgraph(nodes, scope="upstream")`** — the same brief over a **hand-picked** subgraph.
  Pass the nodes to review (a filename / artifact id / version id, or a list); it resolves them to
  seeds, reads their upstream cone, and returns the evidence: the flagged conflicts (`stale_input` /
  `version_mix`), the lineage as consumption edges, the artifact inventory (filename · version ·
  checksum · is-latest), the raw-input boundary, and the cell ids to fetch producing code for. It
  fixes WHAT to look at — you do the reasoning and may walk deeper with your own tools. Use it when
  you want to scope by hand instead of by conversation.
- **`review_selection(nodes, scope="selection")`** — a brief over **EXACTLY** the picked nodes — for
  the cockpit "review this fork, not the trunk I trust" hand-off. Pass the node refs (version ids from
  the cockpit, or filenames / artifact ids). The **structure** is induced down to just the selection
  and the edges among them (not a full lineage cone), but the **verdicts** come from the FULL-project
  audit — so the flags match exactly what the cockpit colours those nodes, even for a `version_mix`
  that rests on inputs outside the selection. Adds `trusted_inputs` (what the selection consumes from
  the excluded region) and `basis: full_project_audit`. Use `review_subgraph` instead when you *want*
  the whole upstream cone in the brief.

All are computed from provenance alone (nothing stored) and are deterministic. A linear revision chain
(reading v1 to write v2) is a supersession, not a conflict, and is not flagged.
'''


def build() -> None:
    import shutil
    DIST.mkdir(parents=True, exist_ok=True)
    src = _kernel_source()
    compile(src, "kernel.py", "exec")   # fail LOUDLY here if the inliner produced invalid Python
    (DIST / "kernel.py").write_text(src)
    (DIST / "SKILL.md").write_text(SKILL_MD.replace("__SKILL_NAME__", SKILL_NAME))
    shell, app_js = _skill_cockpit_html()  # generated from ui/cockpit.html
    (DIST / "cockpit_template.html").write_text(shell)
    (DIST / "cockpit-app.js").write_text(app_js)
    for name, srcpath in ASSETS.items():
        shutil.copyfile(srcpath, DIST / name)
    kb = (DIST / "kernel.py").stat().st_size
    shell_kb = (DIST / "cockpit_template.html").stat().st_size
    app_kb = (DIST / "cockpit-app.js").stat().st_size
    print(f"built {DIST / 'kernel.py'} ({kb} bytes) + SKILL.md + cockpit shell ({shell_kb // 1024} KB) "
          f"+ app js ({app_kb // 1024} KB, saved once) + {len(ASSETS)} assets")


def zip_() -> None:
    z = DIST / f"{SKILL_NAME}.zip"
    with zipfile.ZipFile(z, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.write(DIST / "kernel.py", "kernel.py")
        zf.write(DIST / "SKILL.md", "SKILL.md")
        for name in (*GENERATED, *ASSETS):
            zf.write(DIST / name, name)
    print(f"packaged {z} ({z.stat().st_size // 1024} KB)  (upload via Skills -> Add skill -> Upload a skill)")


def share() -> None:
    # The dev loop. Uploaded skills are NOT on disk (probe: skill_dir_on_disk = not on disk) and the
    # kernel has no __file__, so there's no symlink/direct-write path. Instead stage the built files in
    # the sandbox-readable ~/pg-share (probe: pg_share_read = ok); in CS, host.skills.edit reads them.
    import shutil
    dst = pathlib.Path.home() / "pg-share"
    dst.mkdir(parents=True, exist_ok=True)
    # include the app css/js + bundle so a from-scratch draft (host.skills.edit each file) has every asset
    for f in ("kernel.py", "SKILL.md", *GENERATED, "cytoscape-dagre.bundle.min.js"):
        shutil.copyfile(DIST / f, dst / f"{SKILL_NAME}.{f}")
    print(f"shared -> {dst}/{SKILL_NAME}.*  (in CS: run pg_dev_sync() + start a fresh conversation)")


def watch() -> None:
    import time
    targets = [ROOT / "src", ROOT / "design" / "build_skill.py", ROOT / "design" / "skill_assets",
               ROOT / "ui" / "cockpit.html"]  # the cockpit template is generated from it

    def snap():
        s = {}
        for t in targets:
            if t.is_file():
                s[t] = t.stat().st_mtime
            else:
                for p in list(t.rglob("*.py")) + list(t.rglob("*.html")):
                    s[p] = p.stat().st_mtime
        return s

    print("watching src/ + design/ — rebuild + --share on save (Ctrl-C to stop)")
    last = None
    while True:
        cur = snap()
        if cur != last:
            build()
            share()
            print("  [rebuilt + shared] -> run pg_dev_sync() in CS + start a fresh conversation")
            last = cur
        time.sleep(1.0)


def main(argv: list[str]) -> None:
    global SKILL_NAME
    if "--name" in argv:
        idx = argv.index("--name")
        if idx + 1 >= len(argv):
            sys.exit("--name requires a value")
        SKILL_NAME = argv[idx + 1]
    if "--watch" in argv:
        watch()
        return
    build()
    if "--zip" in argv:
        zip_()
    if "--share" in argv:
        share()


if __name__ == "__main__":
    main(sys.argv[1:])
