"""build_mock.py — the Claude Design bridge for the cockpit.

The repo/served file is always the clean **ui/cockpit.html**. This tool converts between it and the
disposable, git-ignored **ui/cockpit.mock.html** that we hand to Claude Design:

    bake    ui/cockpit.html  --(+ fixtures)-->  ui/cockpit.mock.html   (offline-previewable; push this)
    strip   <design return>  --(- mock block)-->  ui/cockpit.html       (clean again; serve/commit this)

Only the fenced  `// ===== PG:MOCK … /PG:MOCK =====`  block differs between the two files; the PG:DATA-IO
block (the frozen API contract) and all presentation ride through untouched. `bake` is idempotent — it
strips any existing PG:MOCK first — so re-running it on a clean cockpit, a prior mock, or Claude Design's
return all yield the same result. That idempotence is what lets Claude Design be careless with the block.

    uv run python design/build_mock.py bake      # ui/cockpit.html + fixtures -> ui/cockpit.mock.html
    uv run python design/build_mock.py strip      # ui/cockpit.mock.html (or --src FILE) -> ui/cockpit.html
"""

# ruff: noqa: E501 — inlines a JS template + CLI examples that are naturally long

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CLEAN = ROOT / "ui" / "cockpit.html"
MOCK = ROOT / "ui" / "cockpit.mock.html"
FIXTURES = ROOT / "design" / "graph_fixtures.json"

# the whole fenced mock block. `.*` is GREEDY on purpose: it runs to the LAST `/PG:MOCK` marker, so a
# stray copy of the marker inside baked fixture data (a node's `code`) can't truncate the block early.
MOCK_RE = re.compile(r"\n?[ \t]*// ===== PG:MOCK\b.*// ===== /PG:MOCK =====[^\n]*\n?", re.DOTALL)
# the PG:MOCK block is inserted immediately after the last frozen block — after PG:LOG if present
# (so the mock wraps the logged data calls), else after PG:DATA-IO
ANCHORS = ("// ===== /PG:LOG =====", "// ===== /PG:DATA-IO =====")

MOCK_TEMPLATE = """
// ===== PG:MOCK — generated by design/build_mock.py. Do NOT edit or restyle; regenerated each build. =====
// Offline (Claude Design's sandbox, or ?mock): getProjects()/getGraph() serve baked fixtures and the
// PG:LOG POSTs are captured (they can't reach a server). A dev-only, dismissible mock inspector — toggled
// by the ◆ MOCK DATA badge — surfaces both the served fake API calls and the captured log events. Inert on
// our server (the real fetch succeeds, so none of this runs).
(function () {
  const FIXTURES = __FIXTURES__;
  const want = new URLSearchParams(location.search).has("mock");
  const withGraph = FIXTURES.projects.filter(p => FIXTURES.graphs[p.id]);
  const first = Object.keys(FIXTURES.graphs)[0];
  const _p = getProjects, _g = getGraph;
  const feed = [];
  const esc = (s) => String(s).replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c]));
  const note = (kind, text) => { feed.push({ t: new Date().toLocaleTimeString(), kind, text }); if (feed.length > 80) feed.shift(); ui(); };

  getProjects = async () => {
    try { if (want) throw 0; return await _p(); }
    catch (e) { note("api", `getProjects → ${withGraph.length} projects`); return withGraph; }
  };
  getGraph = async (pid) => {
    try { if (want) throw 0; return await _g(pid); }
    catch (e) {
      const g = FIXTURES.graphs[pid] || FIXTURES.graphs[first] || { cs_project_id: pid, nodes: [], edges: [], frames: [], built_at: 0 };
      note("api", `getGraph(${pid}) → ${g.nodes.length} nodes, ${g.edges.length} edges`);
      return g;
    }
  };

  // capture /api/log posts so PG:LOG is visible offline and doesn't error on the dead endpoint
  const _fetch = window.fetch.bind(window);
  window.fetch = (url, init) => {
    if (typeof url === "string" && url === "/api/log" && init && init.body) {
      try { for (const ev of JSON.parse(init.body)) note("log", `${ev.kind} ${ev.name || ev.message || ""}`.trim()); } catch (_) {}
      return Promise.resolve(new Response('{"ok":true}', { status: 200 }));
    }
    return _fetch(url, init);
  };

  let panel;
  function ui() {
    if (!document.body) { document.addEventListener("DOMContentLoaded", ui); return; }
    if (!panel) {
      const badge = document.createElement("button");
      badge.textContent = "◆ MOCK DATA";
      badge.style.cssText = "position:fixed;left:10px;bottom:10px;z-index:99999;font:600 11px ui-monospace,monospace;letter-spacing:.08em;padding:.3rem .55rem;border-radius:6px;background:#d99a2b;color:#1a1a17;border:none;cursor:pointer;box-shadow:0 2px 8px rgba(0,0,0,.28)";
      panel = document.createElement("div");
      panel.style.cssText = "position:fixed;left:10px;bottom:44px;z-index:99999;width:340px;max-height:42vh;overflow:auto;display:none;font:11px ui-monospace,monospace;line-height:1.5;background:#17140d;color:#e9e9e4;border:1px solid #d99a2b;border-radius:8px;padding:.45rem .55rem;box-shadow:0 6px 20px rgba(0,0,0,.45)";
      badge.onclick = () => { panel.style.display = panel.style.display === "none" ? "block" : "none"; };
      document.body.append(badge, panel);
    }
    panel.innerHTML = feed.slice().reverse().map((e) =>
      `<div style="color:${e.kind === "log" ? "#8fd4df" : "#e9e9e4"}"><span style="color:#8a8a80">${e.t}</span> <b>${e.kind}</b> ${esc(e.text)}</div>`
    ).join("") || '<div style="color:#8a8a80">no mock activity yet — interact with the cockpit</div>';
  }
  ui();
})();
// ===== /PG:MOCK =====
"""


def _disp(p: pathlib.Path) -> str:
    """Path relative to the repo root when possible, else absolute — for tidy log lines."""
    try:
        return str(p.relative_to(ROOT))
    except ValueError:
        return str(p)


def strip_mock(html: str) -> str:
    """Remove the fenced PG:MOCK block (if any). Leaves PG:DATA-IO and presentation untouched."""
    return MOCK_RE.sub("", html)


def bake(src: pathlib.Path = CLEAN, out: pathlib.Path = MOCK, vendor_ref: bool = False) -> None:
    if not FIXTURES.exists():
        sys.exit(f"missing {FIXTURES.relative_to(ROOT)} — run: uv run python design/graph_fixtures.py")
    html = strip_mock(src.read_text())  # idempotent: drop any stale block first
    if vendor_ref:
        # Claude Design mock: swap the ~654KB inlined PG:VENDOR for a <script src> to the attached bundle,
        # so the hand-off stays light. The pull re-inlines it (design/vendor_libs.py).
        import vendor_libs
        html = vendor_libs.strip_src_refs(vendor_libs.strip_vendor(html))
        if "</head>" not in html:
            sys.exit("no </head> in the cockpit — cannot place the bundle <script src> for --vendor-ref")
        html = html.replace("</head>", vendor_libs.BUNDLE_TAG + "\n</head>", 1)
    anchor = next((a for a in ANCHORS if a in html), None)
    if anchor is None:
        sys.exit(f"no PG anchor found in {src.name} — is the PG:DATA-IO / PG:LOG block intact?")
    fixtures = json.loads(FIXTURES.read_text())
    # escape "</" so an inlined </script> in any node's code can't close the wrapper tag
    fx = json.dumps(fixtures, separators=(",", ":")).replace("</", "<\\/")
    block = MOCK_TEMPLATE.replace("__FIXTURES__", fx)
    out.write_text(html.replace(anchor, anchor + block, 1))
    mode = "src-ref bundle" if vendor_ref else "inlined vendor"
    print(f"baked {_disp(out)}  ({out.stat().st_size:,} bytes, {len(fixtures['graphs'])} graphs, {mode})")


def strip(src: pathlib.Path = MOCK, out: pathlib.Path = CLEAN) -> None:
    if not src.exists():
        sys.exit(f"missing {src}")
    html = strip_mock(src.read_text())
    # A --vendor-ref design return references the cytoscape bundle by <script src>; the SERVED cockpit must be
    # self-contained, so re-inline the vendor here (idempotent). If the vendored libs aren't present, leave the
    # ref and warn loudly rather than silently ship a cockpit that 404s cytoscape.
    import vendor_libs
    if vendor_libs.SCRIPT_SRC_RE.search(html) and not vendor_libs.VENDOR_RE.search(html):
        if all((vendor_libs.VENDOR / n).exists() for n in vendor_libs.LIBS):
            html = vendor_libs.strip_src_refs(html)
            html = html.replace("</head>", vendor_libs.build_block() + "</head>", 1)
        else:
            print("WARNING: cockpit references the cytoscape bundle by <script src> but ui/vendor/ libs are "
                  "missing — run design/vendor_libs.py, or the served page won't load cytoscape")
    out.write_text(html)
    print(f"stripped {src.name} -> {_disp(out)}  ({out.stat().st_size:,} bytes)")


def main() -> None:
    ap = argparse.ArgumentParser(description="Bake/strip the cockpit mock for the Claude Design round-trip.")
    sub = ap.add_subparsers(dest="cmd", required=True)
    bp = sub.add_parser("bake", help="clean cockpit + fixtures -> mock")
    bp.add_argument("--src", type=pathlib.Path, default=CLEAN, help="clean cockpit to bake from")
    bp.add_argument("--out", type=pathlib.Path, default=MOCK, help="mock file to write")
    bp.add_argument("--vendor-ref", action="store_true",
                    help="Claude Design mock: reference the cytoscape bundle via <script src> (don't inline)")
    sp = sub.add_parser("strip", help="a mock / design-return file -> clean cockpit")
    sp.add_argument("--src", type=pathlib.Path, default=MOCK, help="mock / design-return to strip")
    sp.add_argument("--out", type=pathlib.Path, default=CLEAN, help="clean cockpit to write")
    a = ap.parse_args()
    bake(a.src, a.out, a.vendor_ref) if a.cmd == "bake" else strip(a.src, a.out)


if __name__ == "__main__":
    main()
