"""vendor_libs.py — inline the DAG engine (cytoscape + dagre + cytoscape-dagre) into cockpit.html.

The cockpit must run **offline / self-contained** (brief §2.3): no runtime CDN fetch. So we vendor the
minified libraries once (they live in `ui/vendor/`) and inline them into `ui/cockpit.html` as a **frozen
`PG:VENDOR` block** in `<head>`, before the app script that uses them. Claude Design must not touch this
block; it rides through bake/strip untouched (those only act on the JS-comment `PG:MOCK` fence, a different
marker), so the round-trip and the served file both carry cytoscape with zero external reach.

Idempotent: re-running strips any existing PG:VENDOR first, so it doubles as the version-bump path
(re-fetch into ui/vendor/, re-run). It also converts a Claude-Design return — which references the bundle
via `<script src="./cytoscape-dagre.bundle.min.js">` — into the inline block, so the served file needs no
sibling file or static route. Bytes go disk→disk here — never through a model's token stream.

    uv run python design/vendor_libs.py       # ui/vendor/*.js -> inlined PG:VENDOR block in ui/cockpit.html
"""

# ruff: noqa: E501 — long inline markers, the register snippet, and the src-ref regex are naturally long

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
COCKPIT = ROOT / "ui" / "cockpit.html"
VENDOR = ROOT / "ui" / "vendor"
# load order matters: cytoscape global, then dagre global, then the extension that consumes both
LIBS = ("cytoscape.min.js", "dagre.min.js", "cytoscape-dagre.js")
BUNDLE = "cytoscape-dagre.bundle.min.js"  # the 3 libs concatenated — the one file Claude Design attaches
BUNDLE_TAG = f'<script src="./{BUNDLE}"></script>'  # how the light (src-ref) mock references it

OPEN = "<!-- ===== PG:VENDOR — cytoscape + dagre + cytoscape-dagre, vendored + inlined minified. Frozen; do not edit; regenerated by design/vendor_libs.py. ===== -->"
CLOSE = "<!-- ===== /PG:VENDOR ===== -->"
# register cytoscape-dagre defensively: the UMD may auto-register, so swallow a double-register
REGISTER = "<script>try{if(window.cytoscape&&window.cytoscapeDagre)cytoscape.use(window.cytoscapeDagre);}catch(e){}</script>"

VENDOR_RE = re.compile(r"\n?[ \t]*<!-- ===== PG:VENDOR\b.*/PG:VENDOR =====[^>]*-->\n?", re.DOTALL)


def strip_vendor(html: str) -> str:
    """Remove the PG:VENDOR block (if any). Leaves everything else, incl. PG:DATA-IO/PG:LOG, untouched."""
    return VENDOR_RE.sub("", html)


# a Claude-Design return references the bundle via <script src="./cytoscape-dagre.bundle.min.js">;
# replacing that with the inline block keeps the served file self-contained. Scoped to our exact BUNDLE
# filename so an app-code mention of a lib in a string/comment is never matched.
SCRIPT_SRC_RE = re.compile(
    r"\n?[ \t]*<script\b[^>]*\bsrc=[\"'][^\"']*" + re.escape(BUNDLE) + r"[\"'][^>]*>\s*</script>[^\n]*\n?",
    re.IGNORECASE,
)


def strip_src_refs(html: str) -> str:
    """Drop any <script src=…cytoscape/dagre….js> tag — Claude Design's reference to the attached bundle."""
    return SCRIPT_SRC_RE.sub("", html)


def _require_libs() -> None:
    missing = [n for n in LIBS if not (VENDOR / n).exists()]
    if missing:
        sys.exit(f"missing vendored libs in {VENDOR.relative_to(ROOT)}: {missing}")


def build_block() -> str:
    _require_libs()
    scripts = "\n".join(f"<script>{(VENDOR / n).read_text()}</script>" for n in LIBS)
    return f"\n{OPEN}\n{scripts}\n{REGISTER}\n{CLOSE}\n"


def build_bundle() -> pathlib.Path:
    """Write the single-file bundle Claude Design attaches for the light `<script src>` mock — the same 3 libs
    (+ a defensive register), concatenated (`;`-separated to avoid ASI seams) into ui/vendor/<BUNDLE>."""
    _require_libs()
    body = "\n;\n".join((VENDOR / n).read_text() for n in LIBS)
    reg = "try{if(window.cytoscape&&window.cytoscapeDagre)cytoscape.use(window.cytoscapeDagre);}catch(e){}\n"
    (VENDOR / BUNDLE).write_text(body + "\n;\n" + reg)
    return VENDOR / BUNDLE


def main() -> None:
    if "</head>" not in (html := strip_src_refs(strip_vendor(COCKPIT.read_text()))):
        sys.exit("no </head> in ui/cockpit.html — cannot place the PG:VENDOR block")
    COCKPIT.write_text(html.replace("</head>", build_block() + "</head>", 1))
    print(f"vendored {', '.join(LIBS)} -> ui/cockpit.html  ({COCKPIT.stat().st_size:,} bytes)")
    b = build_bundle()
    print(f"bundle {b.name}  ({b.stat().st_size:,} bytes) — attach this to Claude Design")


if __name__ == "__main__":
    main()
